# .github/workflows/test.yml
name: Test

# Trigger the workflow on push or pull request events
on: [push, pull_request]

jobs:
  test:
    # Run the job on the latest Ubuntu environment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"  # Specify the Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]  # Install your package and test dependencies

      # Step 4: Run tests
      - name: Run tests
        run: |
          python -m pytest